========================================================= test session starts =========================================================
platform darwin -- Python 3.7.5, pytest-5.4.1, py-1.8.1, pluggy-0.13.1
rootdir: /Users/Shel/Projects/BC.gov/aries-protocol-test-suite, inifile: pytest.ini
plugins: asyncio-0.10.0
collected 17 items                                                                                                                    
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/Shel/Projects/BC.gov/aries-protocol-test-suite/env/lib/python3.7/site-packages/_pytest/main.py", line 191, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/Users/Shel/Projects/BC.gov/aries-protocol-test-suite/env/lib/python3.7/site-packages/_pytest/main.py", line 246, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/Users/Shel/Projects/BC.gov/aries-protocol-test-suite/env/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/Users/Shel/Projects/BC.gov/aries-protocol-test-suite/env/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/Shel/Projects/BC.gov/aries-protocol-test-suite/env/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/Users/Shel/Projects/BC.gov/aries-protocol-test-suite/env/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Users/Shel/Projects/BC.gov/aries-protocol-test-suite/env/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/Shel/Projects/BC.gov/aries-protocol-test-suite/env/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/Shel/Projects/BC.gov/aries-protocol-test-suite/env/lib/python3.7/site-packages/_pytest/main.py", line 257, in pytest_collection
INTERNALERROR>     return session.perform_collect()
INTERNALERROR>   File "/Users/Shel/Projects/BC.gov/aries-protocol-test-suite/env/lib/python3.7/site-packages/_pytest/main.py", line 455, in perform_collect
INTERNALERROR>     session=self, config=self.config, items=items
INTERNALERROR>   File "/Users/Shel/Projects/BC.gov/aries-protocol-test-suite/env/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/Users/Shel/Projects/BC.gov/aries-protocol-test-suite/env/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/Shel/Projects/BC.gov/aries-protocol-test-suite/env/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/Users/Shel/Projects/BC.gov/aries-protocol-test-suite/env/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Users/Shel/Projects/BC.gov/aries-protocol-test-suite/env/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/Shel/Projects/BC.gov/aries-protocol-test-suite/env/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/Shel/Projects/BC.gov/aries-protocol-test-suite/conftest.py", line 156, in pytest_collection_modifyitems
INTERNALERROR>     config.hook.pytest_deselected(items=deselected)
INTERNALERROR>   File "/Users/Shel/Projects/BC.gov/aries-protocol-test-suite/env/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/Users/Shel/Projects/BC.gov/aries-protocol-test-suite/env/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/Shel/Projects/BC.gov/aries-protocol-test-suite/env/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/Users/Shel/Projects/BC.gov/aries-protocol-test-suite/env/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Users/Shel/Projects/BC.gov/aries-protocol-test-suite/env/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/Shel/Projects/BC.gov/aries-protocol-test-suite/env/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/Shel/Projects/BC.gov/aries-protocol-test-suite/env/lib/python3.7/site-packages/_pytest/terminal.py", line 431, in pytest_deselected
INTERNALERROR>     self._add_stats("deselected", items)
INTERNALERROR>   File "/Users/Shel/Projects/BC.gov/aries-protocol-test-suite/env/lib/python3.7/site-packages/_pytest/terminal.py", line 400, in _add_stats
INTERNALERROR>     self.stats.setdefault(category, []).extend(items[:])
INTERNALERROR> TypeError: 'set' object is not subscriptable

======================================================== 34 warnings in 1.21s =========================================================