[2020-09-28T04:01:43.372] [INFO] FabricGateway - queryInstantiatedChaincodes XXXXX
[2020-09-28T04:02:13.180] [INFO] SyncPlatform - Updating the client network and other details to DB
[2020-09-28T04:02:42.920] [ERROR] FabricGateway - Failed to get chain info from channel XXXXX :  { FabricError: Query failed. Errors: ["Error: 14 UNAVAILABLE: No connection established"]
    at SingleQueryHandler.evaluate (/opt/explorer/node_modules/fabric-network/lib/impl/query/singlequeryhandler.js:46:23)
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'FabricError' }
[2020-09-28T04:02:42.921] [ERROR] Sync - <<<<<<<<<<<<<<<<<<<<<<<<<< Synchronizer Error >>>>>>>>>>>>>>>>>>>>>
[2020-09-28T04:02:42.921] [ERROR] Sync - TypeError: Cannot read property 'height' of null
    at SyncServices.synchBlocks (/opt/explorer/app/platform/fabric/sync/SyncService.js:385:44)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2020-09-28T04:02:42.921] [INFO] Sync - <<<<<<<<<<<<<<<<<<<<<<<<<< Closing client processor >>>>>>>>>>>>>>>>>>>>>
[2020-09-28T04:02:43.182] [INFO] SyncPlatform - Updating the client network and other details to DB
[2020-09-28T04:02:43.187] [ERROR] Sync - <<<<<<<<<<<<<<<<<<<<<<<<<< Synchronizer Error >>>>>>>>>>>>>>>>>>>>>
[2020-09-28T04:02:43.187] [ERROR] Sync - { FabricError: Query failed. Errors: ["Error: 14 UNAVAILABLE: No connection established"]
    at SingleQueryHandler.evaluate (/opt/explorer/node_modules/fabric-network/lib/impl/query/singlequeryhandler.js:46:23)
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'FabricError' }
[2020-09-28T04:02:43.187] [INFO] Sync - <<<<<<<<<<<<<<<<<<<<<<<<<< Closing client processor >>>>>>>>>>>>>>>>>>>>>
[2020-09-28T04:02:43.188] [ERROR] Sync - <<<<<<<<<<<<<<<<<<<<<<<<<< Synchronizer Error >>>>>>>>>>>>>>>>>>>>>
[2020-09-28T04:02:43.188] [ERROR] Sync - { FabricError: Query failed. Errors: ["Error: REQUEST TIMEOUT"]
    at SingleQueryHandler.evaluate (/opt/explorer/node_modules/fabric-network/lib/impl/query/singlequeryhandler.js:46:23)
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'FabricError' }
[2020-09-28T04:02:43.188] [INFO] Sync - <<<<<<<<<<<<<<<<<<<<<<<<<< Closing client processor >>>>>>>>>>>>>>>>>>>>>
