logs when it wasn't working ```
\\":{\\"txn\\":{\\"type\\":\\"2\\",\\"data\\":{\\"ver\\":\\"1\\",\\"viewNo\\":1,\\"ppSeqNo\\":4,\\"ledgerSize\\":{\\"2\\":0,\\"0\\":4,\\"1\\":5},\\"ledgerRoot\\":{\\"2\\":1,\\"0\\":3,\\"1\\":\\"DJLzEifT7n9DbiCHqQ5KWrWUPFBiZt349popapDfzo5p\\"},\\"stateRoot\\":{\\"1\\":\\"GWEizEWQdGH5QFdxRpoQGvPR42zSUEJoFkQKGBHiNDbM\\"},\\"primaries\\":3,\\"digest\\":\\"cd39463f3aa42924f48825dc5076b55e21bc3c872ff374b916add5160c03eae3\\",\\"nodeReg\\":3},\\"protocolVersion\\":2,\\"metadata\\":{}},\\"txnMetadata\\":{\\"txnTime\\":1612538515,\\"seqNo\\":4},\\"reqSignature\\":{},\\"ver\\":\\"1\\"}},\\"0\\":{\\"Count\\":0},\\"2\\":{\\"Count\\":0},\\"1\\":{\\"Count\\":0}},\\"Uncommitted_state_root_hashes\\":{\\"2\\":\\"b\'DfNLmH4DAHTKv63YPFJzuRdeEtVwF5RtVnvKYHd8iLEA\'\\",\\"0\\":\\"b\'FBxkF5tY2KugsN1A2fwCUCk3RXwtZQxfyXMZy6bvxaAf\'\\",\\"1\\":\\"b\'GWEizEWQdGH5QFdxRpoQGvPR42zSUEJoFkQKGBHiNDbM\'\\"},\\"View_change_status\\":{\\"View_No\\":1,\\"VC_in_progress\\":false,\\"Last_view_change_started_at\\":\\"2021-02-05 15:21:55\\",\\"Last_complete_view_no\\":1,\\"IC_queue\\":{\\"2\\":{\\"Voters\\":{\\"Node1\\":{\\"reason\\":44}}}},\\"VCDone_queue\\":{}},\\"Catchup_status\\":{\\"Ledger_statuses\\":{\\"3\\":\\"synced\\",\\"0\\":\\"synced\\",\\"2\\":\\"synced\\",\\"1\\":\\"synced\\"},\\"Received_LedgerStatus\\":\\"\\",\\"Waiting_consistency_proof_msgs\\":{\\"3\\":null,\\"0\\":null,\\"2\\":null,\\"1\\":null},\\"Number_txns_in_catchup\\":{\\"3\\":0,\\"0\\":0,\\"2\\":0,\\"1\\":0},\\"Last_txn_3PC_keys\\":{\\"3\\":{\\"Node2\\":[null,null],\\"Node4\\":[null,null]},\\"0\\":{\\"Node2\\":[null,null],\\"Node4\\":[null,null]},\\"2\\":{\\"Node2\\":[null,null],\\"Node4\\":[null,null]},\\"1\\":{\\"Node2\\":[null,null],\\"Node4\\":[null,null]}}},\\"Freshness_status\\":{\\"0\\":{\\"Last_updated_time\\":\\"2021-02-05 15:21:55+00:00\\",\\"Has_write_consensus\\":true},\\"1\\":{\\"Last_updated_time\\":\\"2021-02-05 15:21:55+00:00\\",\\"Has_write_consensus\\":true},\\"2\\":{\\"Last_updated_time\\":\\"2021-02-05 15:21:55+00:00\\",\\"Has_write_consensus\\":true}},\\"Requests_timeouts\\":{\\"Propagates_phase_req_timeouts\\":0,\\"Ordering_phase_req_timeouts\\":0},\\"Count_of_replicas\\":2,\\"Replicas_status\\":{\\"Node3:0\\":{\\"Primary\\":\\"Node2:0\\",\\"Watermarks\\":\\"0:300\\",\\"Last_ordered_3PC\\":[1,3],\\"Stashed_txns\\":{\\"Stashed_checkpoints\\":0,\\"Stashed_PrePrepare\\":0}},\\"Node3:1\\":{\\"Primary\\":\\"Node3:1\\",\\"Watermarks\\":\\"0:300\\",\\"Last_ordered_3PC\\":[1,0],\\"Stashed_txns\\":{\\"Stashed_checkpoints\\":0,\\"Stashed_PrePrepare\\":0}}}},\\"Software\\":{\\"OS_version\\":\\"Linux-5.4.0-1029-aws-x86_64-with-debian-buster-sid\\",\\"Installed_packages\\":[\\"zipp 3.1.0\\",\\"yarl 1.4.2\\",\\"wcwidth 0.2.5\\",\\"ujson 1.33\\",\\"typing 3.7.4.1\\",\\"typing-extensions 3.7.4.2\\",\\"timeout-decorator 0.4.0\\",\\"supervisor 4.0.4\\",\\"sortedcontainers 1.5.7\\",\\"six 1.11.0\\",\\"sha3 0.2.1\\",\\"setuptools 40.6.2\\",\\"semver 2.7.9\\",\\"rlp 0.6.0\\",\\"pyzmq 18.1.0\\",\\"PyYAML 5.1.2\\",\\"python3-indy 1.15.0\\",\\"python-ursa 0.1.0\\",\\"python-rocksdb 0.6.9\\",\\"python-dateutil 2.6.1\\",\\"pytest 5.4.3\\",\\"pyparsing 2.4.7\\",\\"Pympler 0.8\\",\\"Pygments 2.2.0\\",\\"pycparser 2.20\\",\\"pycares 3.1.1\\",\\"py 1.8.2\\",\\"psutil 5.4.3\\",\\"prompt-toolkit 0.57\\",\\"portalocker 0.5.7\\",\\"pluggy 0.13.1\\",\\"pip 9.0.3\\",\\"packaging 19.0\\",\\"orderedset 2.0.3\\",\\"multidict 4.7.6\\",\\"msgpack-python 0.4.6\\",\\"more-itertools 8.4.0\\",\\"meld3 2.0.1\\",\\"MarkupSafe 1.1.1\\",\\"libnacl 1.6.1\\",\\"leveldb 0.201\\",\\"jsonpickle 0.9.6\\",\\"Jinja2 2.11.3\\",\\"ioflo 1.5.4\\",\\"intervaltree 2.1.0\\",\\"indy-plenum 1.13.0.dev0\\",\\"indy-node 1.12.3\\",\\"importlib-metadata 1.6.1\\",\\"idna 2.9\\",\\"idna-ssl 1.1.0\\",\\"distro 1.3.0\\",\\"chardet 3.0.4\\",\\"cffi 1.14.0\\",\\"cchardet 2.1.6\\",\\"base58 1.0.3\\",\\"attrs 19.3.0\\",\\"async-timeout 3.0.1\\",\\"aiosqlite 0.10.0\\",\\"aiohttp 3.5.4\\",\\"aiohttp-jinja2 1.1.2\\",\\"aiodns 2.0.0\\"],\\"Indy_packages\\":[\\"\\"],\\"indy-node\\":\\"1.12.3\\",\\"sovrin\\":\\"unknown\\"},\\"Update_time\\":\\"Friday, February 5, 2021 3:23:02 PM +0000\\",\\"Memory_profiler\\":[],\\"Extractions\\":{\\"journalctl_exceptions\\":[\\"\\"],\\"indy-node_status\\":[\\"\\"],\\"node-control status\\":[\\"\\"],\\"upgrade_log\\":\\"\\",\\"stops_stat\\":null}}}}","Node4":"timeout"}'
webserver_1  | 2021-02-05 15:24:02,368|ERROR|server.py|Error retrieving validator info
webserver_1  | Traceback (most recent call last):
webserver_1  |   File "/home/indy/server/server.py", line 100, in status
webserver_1  |     status["validators"] = await TRUST_ANCHOR.validator_info()
webserver_1  |   File "/home/indy/server/anchor.py", line 631, in validator_info
webserver_1  |     reply = json.loads(node_data[node])
webserver_1  |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/json/__init__.py", line 354, in loads
webserver_1  |     return _default_decoder.decode(s)
webserver_1  |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/json/decoder.py", line 339, in decode
webserver_1  |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
webserver_1  |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/json/decoder.py", line 357, in raw_decode
webserver_1  |     raise JSONDecodeError("Expecting value", s, err.value) from None
webserver_1  | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
webserver_1  | 2021-02-05 15:24:02,371|INFO|web_log.py|39.43.33.21 [05/Feb/2021:15:23:02 +0000] "GET /status?validators=1 HTTP/1.1" 200 324 "http://12.333.444.567/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36"
webserver_1  | 2021-02-05 15:24:04,726|INFO|web_log.py|39.43.33.21 [05/Feb/2021:15:24:04 +0000] "GET / HTTP/1.1" 200 10367 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36"
webserver_1  | 2021-02-05 15:24:05,346|INFO|web_log.py|39.43.33.21 [05/Feb/2021:15:24:05 +0000] "GET /status?validators= HTTP/1.1" 200 302 "http://12.333.444.567/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36"
webserver_1  | 2021-02-05 15:24:05,571|INFO|web_log.py|39.43.33.21 [05/Feb/2021:15:24:05 +0000] "GET /favicon.ico HTTP/1.1" 200 22707 "http://12.333.444.567/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36"
webserver_1  | 2021-02-05 15:24:06,595|DEBUG|ledger.py|build_get_validator_info_request: >>> submitter_did: 'V4SGRU86Z58d6TV7PBUe6f'
webserver_1  | 2021-02-05 15:24:06,596|DEBUG|ledger.py|build_get_validator_info_request: <<< res: '{"reqId":1612538646595785198,"identifier":"V4SGRU86Z58d6TV7PBUe6f","operation":{"type":"119"},"protocolVersion":2}'
webserver_1  | 2021-02-05 15:24:06,596|DEBUG|ledger.py|submit_request: >>> pool_handle: 2, request_json: '{"reqId": 1612538646595785198, "identifier": "V4SGRU86Z58d6TV7PBUe6f", "operation": {"type": "119"}, "protocolVersion": 2, "signature": "5zSrF2QJdWfoyygf7GBWANy4dJggfJyqCTpTKj6GxEWknB7Htj3zP4ary4MGqXzU6sRnXpQLEZ1Bd87vHQaL8JEE"}'
```